# Generated by Django 4.2.1 on 2023-06-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('sobrenome', models.CharField(max_length=30)),
                ('idade', models.CharField(max_length=3)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('profissao', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('senha', models.CharField(max_length=12)),
            ],
        ),
    ]
