# Generated by Django 4.2.1 on 2023-06-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_cadastro_usuario_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario_Usuario',
        ),
    ]
